---
- name: This Playbook to set-up Kubernetes using k3s
  hosts: kubcluster
  become: true
  tasks:

  - name: To update the packages
    command: sudo apt-get update

  - name: To install docker
    command: sudo apt install docker.io -y

  - name: To start docker service
    command: sudo systemctl start docker

  - name: To setup kubernetes cluster
    shell:  curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig=/home/ubuntu/.kube/config --write-kubeconfig-mode=644" sh -

  

